### ISSUE TITLE
Proposal for .stxmap protocol for Stacks inscriptions.

### ISSUE THREAD

**Issue by Ghislo749** [fess-v/stx20-standard#1]
Could it be possible to upgrade the indexer in order to implement a protocol to empower a "stxmap" metaverse on Stacks in a similar fashion as "bitmap" for Bitcoin?

The mint/transfer operations could be handled like this:

> {operator}{block_height}{.stxmap}

For example :

`m1000.stxmap` 
`t1000.stxmap`

The 'Block Height' variable could then be used by APIs to retrieve specific blocks data for apps etc etc.

The idea already came up in the STX20 discord, what do you guys think about it?

**Comment by Tazepay** [comment]
I like this idea. However do we need the "m"  when minting?
this adds unnecessary data and makes things less elegant looking.

**Comment by Ghislo749** [comment]
Yeah maybe operator is not 100% necessary. 

I understand the fear that the mint wouldn't be fair as someone might already have minted some in preview of a future implementation. (I'm one of them, don't worry) 

We could run the stxmap indexer to include mints happening only after a specific block height happening in the future. After we decided what the overall consensus is. That would make it fair for everyone. It's going to be a gas war for the rare ones though.

**Comment by fess-v** [comment]
Thanks for the issue @Ghislo749!

Yes, there are lots of requests from the community regarding stxmap and domain names
This first upgrade could include both things at once
@Tazepay is right regarding redundancy in my opinion. 
Both `stxs` domain names and the `stxmap` project can have a similar minting and transferring structure:

`{blockNumber}.stxmap`, where `blockNumber` is an integer and must be less or equal to the current block. I also insist on making the last possible block for stxmap to be set as the Nakamoto mainnet upgrade block, since it will add scarcity and make the project more valuable overall, since after the Nakamoto upgrade blocks will appear once per 5 seconds approximately.

Domains:
`{domainName}.stxs`, where `domainName` is optional and may contain only particular symbols (to be defined).

Both `stxmap` and `stxs` domain names can be claimed once by the first STX transfer inscription.

Transferring can be done using the same minting command.

Activation block is also to be defined, but I think this idea is almost ready to go overall.

**Comment by shreym3578** [comment]
Love this, I also have minted lots stxmaps already, should the early supporters of stxmap be allowed to keep their stxmaps and have them indexed, so would it be better to have the stxmaps just indexed from the beginning of blockchain, because that is what happens in ordinals, and when there’s more websites supporting stacks, would they definitely consider the first inscriptions of stxmap to be valid?

**Comment by Ghislo749** [comment]
Thank you for the answer @fess-v !

Yeah, I have to agree on second thought that the operators are not necessary in these two cases (maps and domains).

Also I like the idea of making as last available block the one before the Nakamoto upgrade. That would add a "cultural" value in the Stacks ecosystem and also fix the issue of inflating supply with 5 sec blocks.

And also agree on defining an "Activation block" for the indexer to make mints fair for the entire community.

**Comment by fess-v** [comment]
After community consultation, it was agreed to index pre-existing domains and stxmaps, adhering to a 'first-come, first-served' principle. Both proposals were ratified, resulting in the reindexing of older transactions to incorporate earlier inscriptions. Furthermore, updates will be made to the interfaces on stx20.com to improve user experience. A big thanks to everyone involved!
